server:
  port: 8081

spring:
  application:
    name: ms-usuarios

  security: 
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/
          tenant-id: 78b145ef-56b9-4397-b87c-27b242a9fce5
  # CONFIGURACIÓN DE DATASOURCE, utilizando variables de entorno para mayor flexibilidad y seguridad
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_usuarios}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}

  # CONFIGURACIÓN DE JPA, para que Hibernate gestione automáticamente las tablas y utilice el dialecto correcto para PostgreSQL
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# CONFIGURACIÓN DE SPRINGDOC PARA LA DOCUMENTACIÓN DE LA API, con opciones para mejorar la experiencia de uso de Swagger UI
springdoc:
  show-actuator: true
  swagger-ui:
    use-root-path: true
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /api/usuarios/v3/api-docs