server:
  port: 8085

spring:
  application:
    name: ms-ordenes

  # CONFIGURACIÓN DE SEGURIDAD (AZURE AD)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/
          tenant-id: 78b145ef-56b9-4397-b87c-27b242a9fce5

  # BASE DE DATOS POSTGRESQL
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_ordenes}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}

  # RABBITMQ
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:admin}

  # JPA E HIBERNATE
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# SWAGGER
springdoc:
  show-actuator: true
  swagger-ui:
    use-root-path: true
    path: /swagger-ui.html
  api-docs:
    path: /api/ordenes/v1/api-docs