-- 1. Crear bases de datos para cada microservicio
CREATE DATABASE db_usuarios;

-- Sección de creación de tablas e inserción de datos para cada microservicio
-- Usuarios
\c db_usuarios

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo VARCHAR(255) UNIQUE NOT NULL,
    direccion VARCHAR(255),
    edad INTEGER NOT NULL CHECK (edad <= 100 AND edad >= 18),
    foto_url VARCHAR(255),
    genero VARCHAR(255) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    ocupacion VARCHAR(255),
    telefono VARCHAR(255) NOT NULL,
    tipo_usuario VARCHAR(100)
);

-- Se eliminó la columna "password" y "session_id" y sus respectivos valores
INSERT INTO usuarios 
(id, correo, direccion, edad, foto_url, genero, nombre, ocupacion, telefono, tipo_usuario) 
VALUES
(1, 'ma@test.com', 'sucasa', 21, 'https://img.com/foto.jpg', 'Binario', 'Mayckol', 'Estudiante', '1231231', 'cliente'),
(3, 'ro.vargas@duocuc.cl', 'xddd', 27, 'img.com', 'Masculino', 'Rodrigo', 'Estudiante', '123123123', 'cliente');

-- Actualizamos el contador de IDs para que el próximo usuario registrado sea el ID 4 (basado en el MAX id)
SELECT setval(pg_get_serial_sequence('usuarios', 'id'), (SELECT MAX(id) FROM usuarios));

-- ==========================================
-- Microservicio: Productos
-- ==========================================
CREATE DATABASE db_productos;

\c db_productos

CREATE TABLE productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(500),
    precio NUMERIC(10, 2) NOT NULL,
    stock INTEGER NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP,
    fecha_actualizacion TIMESTAMP
);

INSERT INTO productos (nombre, descripcion, precio, stock, activo, fecha_creacion, fecha_actualizacion) 
VALUES
('Funko Pop! Naruto Uzumaki', 'Figura coleccionable de vinilo de Naruto Modo Sabio, edición especial', 24990, 15, true, NOW(), NOW()),
('Peluche Snorlax Gigante', 'Peluche súper suave y pachoncito de Snorlax, tamaño 60cm', 39990, 8, true, NOW(), NOW()),
('Katana Nichirin Tanjiro - Demon Slayer', 'Réplica decorativa escala 1:1, ideal para cosplay o exhibición', 119990, 5, true, NOW(), NOW()),
('Figura Articulada Goku (Agotado)', 'Figura de acción de Dragon Ball Z con manos y rostros intercambiables', 34990, 0, true, NOW(), NOW());

SELECT setval(pg_get_serial_sequence('productos', 'id'), (SELECT MAX(id) FROM productos));


-- ==========================================
-- Microservicio: Carrito
-- ==========================================
CREATE DATABASE db_carrito;

\c db_carrito

-- 1. Tabla Padre: carritos
CREATE TABLE carritos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id VARCHAR(255) NOT NULL, -- Recibe el ID del token de Azure AD/Microsoft
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    estado VARCHAR(50) NOT NULL DEFAULT 'ACTIVO'
);

-- 2. Tabla Hija: items_carrito
CREATE TABLE items_carrito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrito_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL, 
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(10, 2) NOT NULL,
    subtotal NUMERIC(10, 2) NOT NULL,
    CONSTRAINT fk_carrito 
        FOREIGN KEY (carrito_id) 
        REFERENCES carritos(id) 
        ON DELETE CASCADE
);
