server:
  port: 8083

spring:
  application:
    name: ms-carrito

  # CONFIGURACIÓN DE SEGURIDAD (AZURE AD)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/
          tenant-id: 78b145ef-56b9-4397-b87c-27b242a9fce5

  # CONFIGURACIÓN DE BASE DE DATOS POSTGRESQL
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_carrito}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}

  # CONFIGURACIÓN DE RABBITMQ
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:admin}

  # CONFIGURACIÓN DE JPA E HIBERNATE
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

producto:
  api:
    url: ${PRODUCTO_API_URL:http://ms-producto:8082/api/v1/productos}